<?php



/**
 * This class defines the structure of the 'providers_2011' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:55 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class Providers2011TableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Providers2011TableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('providers_2011');
		$this->setPhpName('Providers2011');
		$this->setClassname('Providers2011');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('providers_2011_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'BIGINT', true, null, null);
		$this->addColumn('PROVIDERID', 'Providerid', 'INTEGER', false, null, null);
		$this->addColumn('NAMEZN', 'Namezn', 'VARCHAR', false, null, null);
		$this->addColumn('NAMEEN', 'Nameen', 'VARCHAR', false, null, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, null, null);
		$this->addColumn('PHONEINFO', 'Phoneinfo', 'VARCHAR', false, null, null);
		$this->addColumn('STATIONID', 'Stationid', 'INTEGER', false, null, null);
		$this->addColumn('STATIONNAMEZN', 'Stationnamezn', 'VARCHAR', false, null, null);
		$this->addColumn('STATIONNAMEEN', 'Stationnameen', 'VARCHAR', false, null, null);
		$this->addColumn('TYPE', 'Type', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Providers2011TableMap
