<?php



/**
 * This class defines the structure of the 'routes_2011' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:55 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class Routes2011TableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Routes2011TableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('routes_2011');
		$this->setPhpName('Routes2011');
		$this->setClassname('Routes2011');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('routes_2011_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'BIGINT', true, null, null);
		$this->addColumn('ROUTEID', 'Routeid', 'INTEGER', false, null, null);
		$this->addColumn('PROVIDERID', 'Providerid', 'INTEGER', false, null, null);
		$this->addColumn('PROVIDERNAME', 'Providername', 'VARCHAR', false, null, null);
		$this->addColumn('NAMEZH', 'Namezh', 'VARCHAR', false, null, null);
		$this->addColumn('NAMEEN', 'Nameen', 'VARCHAR', false, null, null);
		$this->addColumn('PATHATTRIBUTEID', 'Pathattributeid', 'INTEGER', false, null, null);
		$this->addColumn('PATHATTRIBUTENAME', 'Pathattributename', 'VARCHAR', false, null, null);
		$this->addColumn('PATHATTRIBUTEENAME', 'Pathattributeename', 'VARCHAR', false, null, null);
		$this->addColumn('BUILDPERIOD', 'Buildperiod', 'INTEGER', false, null, null);
		$this->addColumn('DEPARTUREZH', 'Departurezh', 'VARCHAR', false, null, null);
		$this->addColumn('DEPARTUREEN', 'Departureen', 'VARCHAR', false, null, null);
		$this->addColumn('DESTINATIONZH', 'Destinationzh', 'VARCHAR', false, null, null);
		$this->addColumn('DESTINATIONEN', 'Destinationen', 'VARCHAR', false, null, null);
		$this->addColumn('REALSEQUENCE', 'Realsequence', 'INTEGER', false, null, null);
		$this->addColumn('DISTANCE', 'Distance', 'INTEGER', false, null, null);
		$this->addColumn('GOFIRSTBUSTIME', 'Gofirstbustime', 'VARCHAR', false, null, null);
		$this->addColumn('BACKFIRSTBUSTIME', 'Backfirstbustime', 'VARCHAR', false, null, null);
		$this->addColumn('GOLASTBUSTIME', 'Golastbustime', 'VARCHAR', false, null, null);
		$this->addColumn('BACKLASTBUSTIME', 'Backlastbustime', 'VARCHAR', false, null, null);
		$this->addColumn('OFFPEAKHEADWAY', 'Offpeakheadway', 'VARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Routes2011TableMap
