<?php



/**
 * This class defines the structure of the 'buses_2011_01' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:55 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class Buses201101TableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Buses201101TableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('buses_2011_01');
		$this->setPhpName('Buses201101');
		$this->setClassname('Buses201101');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('buses_2011_01_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'BIGINT', true, null, null);
		$this->addColumn('STATIONID', 'Stationid', 'INTEGER', false, null, null);
		$this->addColumn('CARTYPE', 'Cartype', 'INTEGER', false, null, null);
		$this->addColumn('BUSID', 'Busid', 'VARCHAR', false, null, null);
		$this->addColumn('PROVIDERID', 'Providerid', 'INTEGER', false, null, null);
		$this->addColumn('CARID', 'Carid', 'INTEGER', false, null, null);
		$this->addColumn('DUTYSTATUS', 'Dutystatus', 'INTEGER', false, null, null);
		$this->addColumn('BUSSTATUS', 'Busstatus', 'INTEGER', false, null, null);
		$this->addColumn('ROUTEID', 'Routeid', 'INTEGER', false, null, null);
		$this->addColumn('GOBACK', 'Goback', 'INTEGER', false, null, null);
		$this->addColumn('LONGITUDE', 'Longitude', 'DOUBLE', false, null, null);
		$this->addColumn('LATITUDE', 'Latitude', 'DOUBLE', false, null, null);
		$this->addColumn('SPEED', 'Speed', 'DOUBLE', false, null, null);
		$this->addColumn('AZIMUTH', 'Azimuth', 'DOUBLE', false, null, null);
		$this->addColumn('DATATIME', 'Datatime', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Buses201101TableMap
