<?php



/**
 * This class defines the structure of the 'PresidentialElection2004' table.
 *
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:54 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class Presidentialelection2004TableMap extends TableMap
{

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.Presidentialelection2004TableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('PresidentialElection2004');
		$this->setPhpName('Presidentialelection2004');
		$this->setClassname('Presidentialelection2004');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('PresidentialElection2004_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('COUNTY', 'County', 'VARCHAR', false, null, null);
		$this->addColumn('CITY', 'City', 'VARCHAR', false, null, null);
		$this->addColumn('VILLAGE', 'Village', 'VARCHAR', false, null, null);
		$this->addColumn('VOTENO', 'Voteno', 'INTEGER', false, null, null);
		$this->addColumn('DPPNUM', 'Dppnum', 'INTEGER', false, null, null);
		$this->addColumn('DPPRATIO', 'Dppratio', 'FLOAT', false, null, null);
		$this->addColumn('KMTNUM', 'Kmtnum', 'INTEGER', false, null, null);
		$this->addColumn('KMTRATIO', 'Kmtratio', 'FLOAT', false, null, null);
		$this->addColumn('VAILDVOTES', 'Vaildvotes', 'INTEGER', false, null, null);
		$this->addColumn('INVAILDVOTES', 'Invaildvotes', 'INTEGER', false, null, null);
		$this->addColumn('TOTALVOTES', 'Totalvotes', 'INTEGER', false, null, null);
		$this->addColumn('OTHERVOTES', 'Othervotes', 'INTEGER', false, null, null);
		$this->addColumn('VOTERSNUM', 'Votersnum', 'INTEGER', false, null, null);
		$this->addColumn('VOTERSRATIO', 'Votersratio', 'FLOAT', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // Presidentialelection2004TableMap
