<?php


/**
 * Base class that represents a row from the 'stops_2011' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:55 2012
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseStops2011 extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'Stops2011Peer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Stops2011Peer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the stopid field.
	 * @var        int
	 */
	protected $stopid;

	/**
	 * The value for the routeid field.
	 * @var        int
	 */
	protected $routeid;

	/**
	 * The value for the namezh field.
	 * @var        string
	 */
	protected $namezh;

	/**
	 * The value for the nameen field.
	 * @var        string
	 */
	protected $nameen;

	/**
	 * The value for the seqno field.
	 * @var        int
	 */
	protected $seqno;

	/**
	 * The value for the pgp field.
	 * @var        int
	 */
	protected $pgp;

	/**
	 * The value for the goback field.
	 * @var        int
	 */
	protected $goback;

	/**
	 * The value for the longitude field.
	 * @var        double
	 */
	protected $longitude;

	/**
	 * The value for the latitude field.
	 * @var        double
	 */
	protected $latitude;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the stoplocationid field.
	 * @var        int
	 */
	protected $stoplocationid;

	/**
	 * The value for the showlon field.
	 * @var        double
	 */
	protected $showlon;

	/**
	 * The value for the showlat field.
	 * @var        double
	 */
	protected $showlat;

	/**
	 * The value for the vector field.
	 * @var        int
	 */
	protected $vector;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [stopid] column value.
	 * 
	 * @return     int
	 */
	public function getStopid()
	{
		return $this->stopid;
	}

	/**
	 * Get the [routeid] column value.
	 * 
	 * @return     int
	 */
	public function getRouteid()
	{
		return $this->routeid;
	}

	/**
	 * Get the [namezh] column value.
	 * 
	 * @return     string
	 */
	public function getNamezh()
	{
		return $this->namezh;
	}

	/**
	 * Get the [nameen] column value.
	 * 
	 * @return     string
	 */
	public function getNameen()
	{
		return $this->nameen;
	}

	/**
	 * Get the [seqno] column value.
	 * 
	 * @return     int
	 */
	public function getSeqno()
	{
		return $this->seqno;
	}

	/**
	 * Get the [pgp] column value.
	 * 
	 * @return     int
	 */
	public function getPgp()
	{
		return $this->pgp;
	}

	/**
	 * Get the [goback] column value.
	 * 
	 * @return     int
	 */
	public function getGoback()
	{
		return $this->goback;
	}

	/**
	 * Get the [longitude] column value.
	 * 
	 * @return     double
	 */
	public function getLongitude()
	{
		return $this->longitude;
	}

	/**
	 * Get the [latitude] column value.
	 * 
	 * @return     double
	 */
	public function getLatitude()
	{
		return $this->latitude;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [stoplocationid] column value.
	 * 
	 * @return     int
	 */
	public function getStoplocationid()
	{
		return $this->stoplocationid;
	}

	/**
	 * Get the [showlon] column value.
	 * 
	 * @return     double
	 */
	public function getShowlon()
	{
		return $this->showlon;
	}

	/**
	 * Get the [showlat] column value.
	 * 
	 * @return     double
	 */
	public function getShowlat()
	{
		return $this->showlat;
	}

	/**
	 * Get the [vector] column value.
	 * 
	 * @return     int
	 */
	public function getVector()
	{
		return $this->vector;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = Stops2011Peer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [stopid] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setStopid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stopid !== $v) {
			$this->stopid = $v;
			$this->modifiedColumns[] = Stops2011Peer::STOPID;
		}

		return $this;
	} // setStopid()

	/**
	 * Set the value of [routeid] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setRouteid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->routeid !== $v) {
			$this->routeid = $v;
			$this->modifiedColumns[] = Stops2011Peer::ROUTEID;
		}

		return $this;
	} // setRouteid()

	/**
	 * Set the value of [namezh] column.
	 * 
	 * @param      string $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setNamezh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->namezh !== $v) {
			$this->namezh = $v;
			$this->modifiedColumns[] = Stops2011Peer::NAMEZH;
		}

		return $this;
	} // setNamezh()

	/**
	 * Set the value of [nameen] column.
	 * 
	 * @param      string $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setNameen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nameen !== $v) {
			$this->nameen = $v;
			$this->modifiedColumns[] = Stops2011Peer::NAMEEN;
		}

		return $this;
	} // setNameen()

	/**
	 * Set the value of [seqno] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setSeqno($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->seqno !== $v) {
			$this->seqno = $v;
			$this->modifiedColumns[] = Stops2011Peer::SEQNO;
		}

		return $this;
	} // setSeqno()

	/**
	 * Set the value of [pgp] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setPgp($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pgp !== $v) {
			$this->pgp = $v;
			$this->modifiedColumns[] = Stops2011Peer::PGP;
		}

		return $this;
	} // setPgp()

	/**
	 * Set the value of [goback] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setGoback($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->goback !== $v) {
			$this->goback = $v;
			$this->modifiedColumns[] = Stops2011Peer::GOBACK;
		}

		return $this;
	} // setGoback()

	/**
	 * Set the value of [longitude] column.
	 * 
	 * @param      double $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setLongitude($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->longitude !== $v) {
			$this->longitude = $v;
			$this->modifiedColumns[] = Stops2011Peer::LONGITUDE;
		}

		return $this;
	} // setLongitude()

	/**
	 * Set the value of [latitude] column.
	 * 
	 * @param      double $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setLatitude($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->latitude !== $v) {
			$this->latitude = $v;
			$this->modifiedColumns[] = Stops2011Peer::LATITUDE;
		}

		return $this;
	} // setLatitude()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = Stops2011Peer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [stoplocationid] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setStoplocationid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stoplocationid !== $v) {
			$this->stoplocationid = $v;
			$this->modifiedColumns[] = Stops2011Peer::STOPLOCATIONID;
		}

		return $this;
	} // setStoplocationid()

	/**
	 * Set the value of [showlon] column.
	 * 
	 * @param      double $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setShowlon($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->showlon !== $v) {
			$this->showlon = $v;
			$this->modifiedColumns[] = Stops2011Peer::SHOWLON;
		}

		return $this;
	} // setShowlon()

	/**
	 * Set the value of [showlat] column.
	 * 
	 * @param      double $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setShowlat($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->showlat !== $v) {
			$this->showlat = $v;
			$this->modifiedColumns[] = Stops2011Peer::SHOWLAT;
		}

		return $this;
	} // setShowlat()

	/**
	 * Set the value of [vector] column.
	 * 
	 * @param      int $v new value
	 * @return     Stops2011 The current object (for fluent API support)
	 */
	public function setVector($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->vector !== $v) {
			$this->vector = $v;
			$this->modifiedColumns[] = Stops2011Peer::VECTOR;
		}

		return $this;
	} // setVector()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->stopid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->routeid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->namezh = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->nameen = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->seqno = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->pgp = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->goback = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->longitude = ($row[$startcol + 8] !== null) ? (double) $row[$startcol + 8] : null;
			$this->latitude = ($row[$startcol + 9] !== null) ? (double) $row[$startcol + 9] : null;
			$this->address = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->stoplocationid = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->showlon = ($row[$startcol + 12] !== null) ? (double) $row[$startcol + 12] : null;
			$this->showlat = ($row[$startcol + 13] !== null) ? (double) $row[$startcol + 13] : null;
			$this->vector = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 15; // 15 = Stops2011Peer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating Stops2011 object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Stops2011Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Stops2011Peer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Stops2011Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = Stops2011Query::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStops2011:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStops2011:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Stops2011Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseStops2011:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseStops2011:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				Stops2011Peer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;

		$this->modifiedColumns[] = Stops2011Peer::ID;
		if (null !== $this->id) {
			throw new PropelException('Cannot insert a value for auto-increment primary key (' . Stops2011Peer::ID . ')');
		}
		if (null === $this->id) {
			try {				
				$stmt = $con->query("SELECT nextval('stops_2011_id_seq')");
				$row = $stmt->fetch(PDO::FETCH_NUM);
				$this->id = $row[0];
			} catch (Exception $e) {
				throw new PropelException('Unable to get sequence id.', $e);
			}
		}


		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(Stops2011Peer::ID)) {
			$modifiedColumns[':p' . $index++]  = 'ID';
		}
		if ($this->isColumnModified(Stops2011Peer::STOPID)) {
			$modifiedColumns[':p' . $index++]  = 'STOPID';
		}
		if ($this->isColumnModified(Stops2011Peer::ROUTEID)) {
			$modifiedColumns[':p' . $index++]  = 'ROUTEID';
		}
		if ($this->isColumnModified(Stops2011Peer::NAMEZH)) {
			$modifiedColumns[':p' . $index++]  = 'NAMEZH';
		}
		if ($this->isColumnModified(Stops2011Peer::NAMEEN)) {
			$modifiedColumns[':p' . $index++]  = 'NAMEEN';
		}
		if ($this->isColumnModified(Stops2011Peer::SEQNO)) {
			$modifiedColumns[':p' . $index++]  = 'SEQNO';
		}
		if ($this->isColumnModified(Stops2011Peer::PGP)) {
			$modifiedColumns[':p' . $index++]  = 'PGP';
		}
		if ($this->isColumnModified(Stops2011Peer::GOBACK)) {
			$modifiedColumns[':p' . $index++]  = 'GOBACK';
		}
		if ($this->isColumnModified(Stops2011Peer::LONGITUDE)) {
			$modifiedColumns[':p' . $index++]  = 'LONGITUDE';
		}
		if ($this->isColumnModified(Stops2011Peer::LATITUDE)) {
			$modifiedColumns[':p' . $index++]  = 'LATITUDE';
		}
		if ($this->isColumnModified(Stops2011Peer::ADDRESS)) {
			$modifiedColumns[':p' . $index++]  = 'ADDRESS';
		}
		if ($this->isColumnModified(Stops2011Peer::STOPLOCATIONID)) {
			$modifiedColumns[':p' . $index++]  = 'STOPLOCATIONID';
		}
		if ($this->isColumnModified(Stops2011Peer::SHOWLON)) {
			$modifiedColumns[':p' . $index++]  = 'SHOWLON';
		}
		if ($this->isColumnModified(Stops2011Peer::SHOWLAT)) {
			$modifiedColumns[':p' . $index++]  = 'SHOWLAT';
		}
		if ($this->isColumnModified(Stops2011Peer::VECTOR)) {
			$modifiedColumns[':p' . $index++]  = 'VECTOR';
		}

		$sql = sprintf(
			'INSERT INTO stops_2011 (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case 'ID':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
						break;
					case 'STOPID':
						$stmt->bindValue($identifier, $this->stopid, PDO::PARAM_INT);
						break;
					case 'ROUTEID':
						$stmt->bindValue($identifier, $this->routeid, PDO::PARAM_INT);
						break;
					case 'NAMEZH':
						$stmt->bindValue($identifier, $this->namezh, PDO::PARAM_STR);
						break;
					case 'NAMEEN':
						$stmt->bindValue($identifier, $this->nameen, PDO::PARAM_STR);
						break;
					case 'SEQNO':
						$stmt->bindValue($identifier, $this->seqno, PDO::PARAM_INT);
						break;
					case 'PGP':
						$stmt->bindValue($identifier, $this->pgp, PDO::PARAM_INT);
						break;
					case 'GOBACK':
						$stmt->bindValue($identifier, $this->goback, PDO::PARAM_INT);
						break;
					case 'LONGITUDE':
						$stmt->bindValue($identifier, $this->longitude, PDO::PARAM_STR);
						break;
					case 'LATITUDE':
						$stmt->bindValue($identifier, $this->latitude, PDO::PARAM_STR);
						break;
					case 'ADDRESS':
						$stmt->bindValue($identifier, $this->address, PDO::PARAM_STR);
						break;
					case 'STOPLOCATIONID':
						$stmt->bindValue($identifier, $this->stoplocationid, PDO::PARAM_INT);
						break;
					case 'SHOWLON':
						$stmt->bindValue($identifier, $this->showlon, PDO::PARAM_STR);
						break;
					case 'SHOWLAT':
						$stmt->bindValue($identifier, $this->showlat, PDO::PARAM_STR);
						break;
					case 'VECTOR':
						$stmt->bindValue($identifier, $this->vector, PDO::PARAM_INT);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = Stops2011Peer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Stops2011Peer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getStopid();
				break;
			case 2:
				return $this->getRouteid();
				break;
			case 3:
				return $this->getNamezh();
				break;
			case 4:
				return $this->getNameen();
				break;
			case 5:
				return $this->getSeqno();
				break;
			case 6:
				return $this->getPgp();
				break;
			case 7:
				return $this->getGoback();
				break;
			case 8:
				return $this->getLongitude();
				break;
			case 9:
				return $this->getLatitude();
				break;
			case 10:
				return $this->getAddress();
				break;
			case 11:
				return $this->getStoplocationid();
				break;
			case 12:
				return $this->getShowlon();
				break;
			case 13:
				return $this->getShowlat();
				break;
			case 14:
				return $this->getVector();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
	{
		if (isset($alreadyDumpedObjects['Stops2011'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['Stops2011'][$this->getPrimaryKey()] = true;
		$keys = Stops2011Peer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getStopid(),
			$keys[2] => $this->getRouteid(),
			$keys[3] => $this->getNamezh(),
			$keys[4] => $this->getNameen(),
			$keys[5] => $this->getSeqno(),
			$keys[6] => $this->getPgp(),
			$keys[7] => $this->getGoback(),
			$keys[8] => $this->getLongitude(),
			$keys[9] => $this->getLatitude(),
			$keys[10] => $this->getAddress(),
			$keys[11] => $this->getStoplocationid(),
			$keys[12] => $this->getShowlon(),
			$keys[13] => $this->getShowlat(),
			$keys[14] => $this->getVector(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Stops2011Peer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setStopid($value);
				break;
			case 2:
				$this->setRouteid($value);
				break;
			case 3:
				$this->setNamezh($value);
				break;
			case 4:
				$this->setNameen($value);
				break;
			case 5:
				$this->setSeqno($value);
				break;
			case 6:
				$this->setPgp($value);
				break;
			case 7:
				$this->setGoback($value);
				break;
			case 8:
				$this->setLongitude($value);
				break;
			case 9:
				$this->setLatitude($value);
				break;
			case 10:
				$this->setAddress($value);
				break;
			case 11:
				$this->setStoplocationid($value);
				break;
			case 12:
				$this->setShowlon($value);
				break;
			case 13:
				$this->setShowlat($value);
				break;
			case 14:
				$this->setVector($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Stops2011Peer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setStopid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRouteid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNamezh($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNameen($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSeqno($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPgp($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setGoback($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setLongitude($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setLatitude($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAddress($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setStoplocationid($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setShowlon($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setShowlat($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setVector($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Stops2011Peer::DATABASE_NAME);

		if ($this->isColumnModified(Stops2011Peer::ID)) $criteria->add(Stops2011Peer::ID, $this->id);
		if ($this->isColumnModified(Stops2011Peer::STOPID)) $criteria->add(Stops2011Peer::STOPID, $this->stopid);
		if ($this->isColumnModified(Stops2011Peer::ROUTEID)) $criteria->add(Stops2011Peer::ROUTEID, $this->routeid);
		if ($this->isColumnModified(Stops2011Peer::NAMEZH)) $criteria->add(Stops2011Peer::NAMEZH, $this->namezh);
		if ($this->isColumnModified(Stops2011Peer::NAMEEN)) $criteria->add(Stops2011Peer::NAMEEN, $this->nameen);
		if ($this->isColumnModified(Stops2011Peer::SEQNO)) $criteria->add(Stops2011Peer::SEQNO, $this->seqno);
		if ($this->isColumnModified(Stops2011Peer::PGP)) $criteria->add(Stops2011Peer::PGP, $this->pgp);
		if ($this->isColumnModified(Stops2011Peer::GOBACK)) $criteria->add(Stops2011Peer::GOBACK, $this->goback);
		if ($this->isColumnModified(Stops2011Peer::LONGITUDE)) $criteria->add(Stops2011Peer::LONGITUDE, $this->longitude);
		if ($this->isColumnModified(Stops2011Peer::LATITUDE)) $criteria->add(Stops2011Peer::LATITUDE, $this->latitude);
		if ($this->isColumnModified(Stops2011Peer::ADDRESS)) $criteria->add(Stops2011Peer::ADDRESS, $this->address);
		if ($this->isColumnModified(Stops2011Peer::STOPLOCATIONID)) $criteria->add(Stops2011Peer::STOPLOCATIONID, $this->stoplocationid);
		if ($this->isColumnModified(Stops2011Peer::SHOWLON)) $criteria->add(Stops2011Peer::SHOWLON, $this->showlon);
		if ($this->isColumnModified(Stops2011Peer::SHOWLAT)) $criteria->add(Stops2011Peer::SHOWLAT, $this->showlat);
		if ($this->isColumnModified(Stops2011Peer::VECTOR)) $criteria->add(Stops2011Peer::VECTOR, $this->vector);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Stops2011Peer::DATABASE_NAME);
		$criteria->add(Stops2011Peer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Stops2011 (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setStopid($this->getStopid());
		$copyObj->setRouteid($this->getRouteid());
		$copyObj->setNamezh($this->getNamezh());
		$copyObj->setNameen($this->getNameen());
		$copyObj->setSeqno($this->getSeqno());
		$copyObj->setPgp($this->getPgp());
		$copyObj->setGoback($this->getGoback());
		$copyObj->setLongitude($this->getLongitude());
		$copyObj->setLatitude($this->getLatitude());
		$copyObj->setAddress($this->getAddress());
		$copyObj->setStoplocationid($this->getStoplocationid());
		$copyObj->setShowlon($this->getShowlon());
		$copyObj->setShowlat($this->getShowlat());
		$copyObj->setVector($this->getVector());
		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Stops2011 Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Stops2011Peer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Stops2011Peer();
		}
		return self::$peer;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->stopid = null;
		$this->routeid = null;
		$this->namezh = null;
		$this->nameen = null;
		$this->seqno = null;
		$this->pgp = null;
		$this->goback = null;
		$this->longitude = null;
		$this->latitude = null;
		$this->address = null;
		$this->stoplocationid = null;
		$this->showlon = null;
		$this->showlat = null;
		$this->vector = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(Stops2011Peer::DEFAULT_STRING_FORMAT);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseStops2011:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseStops2011
