<?php


/**
 * Base class that represents a row from the 'routes_2011' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Jan 11 23:40:55 2012
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseRoutes2011 extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
	const PEER = 'Routes2011Peer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        Routes2011Peer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the routeid field.
	 * @var        int
	 */
	protected $routeid;

	/**
	 * The value for the providerid field.
	 * @var        int
	 */
	protected $providerid;

	/**
	 * The value for the providername field.
	 * @var        string
	 */
	protected $providername;

	/**
	 * The value for the namezh field.
	 * @var        string
	 */
	protected $namezh;

	/**
	 * The value for the nameen field.
	 * @var        string
	 */
	protected $nameen;

	/**
	 * The value for the pathattributeid field.
	 * @var        int
	 */
	protected $pathattributeid;

	/**
	 * The value for the pathattributename field.
	 * @var        string
	 */
	protected $pathattributename;

	/**
	 * The value for the pathattributeename field.
	 * @var        string
	 */
	protected $pathattributeename;

	/**
	 * The value for the buildperiod field.
	 * @var        int
	 */
	protected $buildperiod;

	/**
	 * The value for the departurezh field.
	 * @var        string
	 */
	protected $departurezh;

	/**
	 * The value for the departureen field.
	 * @var        string
	 */
	protected $departureen;

	/**
	 * The value for the destinationzh field.
	 * @var        string
	 */
	protected $destinationzh;

	/**
	 * The value for the destinationen field.
	 * @var        string
	 */
	protected $destinationen;

	/**
	 * The value for the realsequence field.
	 * @var        int
	 */
	protected $realsequence;

	/**
	 * The value for the distance field.
	 * @var        int
	 */
	protected $distance;

	/**
	 * The value for the gofirstbustime field.
	 * @var        string
	 */
	protected $gofirstbustime;

	/**
	 * The value for the backfirstbustime field.
	 * @var        string
	 */
	protected $backfirstbustime;

	/**
	 * The value for the golastbustime field.
	 * @var        string
	 */
	protected $golastbustime;

	/**
	 * The value for the backlastbustime field.
	 * @var        string
	 */
	protected $backlastbustime;

	/**
	 * The value for the offpeakheadway field.
	 * @var        string
	 */
	protected $offpeakheadway;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [routeid] column value.
	 * 
	 * @return     int
	 */
	public function getRouteid()
	{
		return $this->routeid;
	}

	/**
	 * Get the [providerid] column value.
	 * 
	 * @return     int
	 */
	public function getProviderid()
	{
		return $this->providerid;
	}

	/**
	 * Get the [providername] column value.
	 * 
	 * @return     string
	 */
	public function getProvidername()
	{
		return $this->providername;
	}

	/**
	 * Get the [namezh] column value.
	 * 
	 * @return     string
	 */
	public function getNamezh()
	{
		return $this->namezh;
	}

	/**
	 * Get the [nameen] column value.
	 * 
	 * @return     string
	 */
	public function getNameen()
	{
		return $this->nameen;
	}

	/**
	 * Get the [pathattributeid] column value.
	 * 
	 * @return     int
	 */
	public function getPathattributeid()
	{
		return $this->pathattributeid;
	}

	/**
	 * Get the [pathattributename] column value.
	 * 
	 * @return     string
	 */
	public function getPathattributename()
	{
		return $this->pathattributename;
	}

	/**
	 * Get the [pathattributeename] column value.
	 * 
	 * @return     string
	 */
	public function getPathattributeename()
	{
		return $this->pathattributeename;
	}

	/**
	 * Get the [buildperiod] column value.
	 * 
	 * @return     int
	 */
	public function getBuildperiod()
	{
		return $this->buildperiod;
	}

	/**
	 * Get the [departurezh] column value.
	 * 
	 * @return     string
	 */
	public function getDeparturezh()
	{
		return $this->departurezh;
	}

	/**
	 * Get the [departureen] column value.
	 * 
	 * @return     string
	 */
	public function getDepartureen()
	{
		return $this->departureen;
	}

	/**
	 * Get the [destinationzh] column value.
	 * 
	 * @return     string
	 */
	public function getDestinationzh()
	{
		return $this->destinationzh;
	}

	/**
	 * Get the [destinationen] column value.
	 * 
	 * @return     string
	 */
	public function getDestinationen()
	{
		return $this->destinationen;
	}

	/**
	 * Get the [realsequence] column value.
	 * 
	 * @return     int
	 */
	public function getRealsequence()
	{
		return $this->realsequence;
	}

	/**
	 * Get the [distance] column value.
	 * 
	 * @return     int
	 */
	public function getDistance()
	{
		return $this->distance;
	}

	/**
	 * Get the [gofirstbustime] column value.
	 * 
	 * @return     string
	 */
	public function getGofirstbustime()
	{
		return $this->gofirstbustime;
	}

	/**
	 * Get the [backfirstbustime] column value.
	 * 
	 * @return     string
	 */
	public function getBackfirstbustime()
	{
		return $this->backfirstbustime;
	}

	/**
	 * Get the [golastbustime] column value.
	 * 
	 * @return     string
	 */
	public function getGolastbustime()
	{
		return $this->golastbustime;
	}

	/**
	 * Get the [backlastbustime] column value.
	 * 
	 * @return     string
	 */
	public function getBacklastbustime()
	{
		return $this->backlastbustime;
	}

	/**
	 * Get the [offpeakheadway] column value.
	 * 
	 * @return     string
	 */
	public function getOffpeakheadway()
	{
		return $this->offpeakheadway;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = Routes2011Peer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [routeid] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setRouteid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->routeid !== $v) {
			$this->routeid = $v;
			$this->modifiedColumns[] = Routes2011Peer::ROUTEID;
		}

		return $this;
	} // setRouteid()

	/**
	 * Set the value of [providerid] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setProviderid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->providerid !== $v) {
			$this->providerid = $v;
			$this->modifiedColumns[] = Routes2011Peer::PROVIDERID;
		}

		return $this;
	} // setProviderid()

	/**
	 * Set the value of [providername] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setProvidername($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->providername !== $v) {
			$this->providername = $v;
			$this->modifiedColumns[] = Routes2011Peer::PROVIDERNAME;
		}

		return $this;
	} // setProvidername()

	/**
	 * Set the value of [namezh] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setNamezh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->namezh !== $v) {
			$this->namezh = $v;
			$this->modifiedColumns[] = Routes2011Peer::NAMEZH;
		}

		return $this;
	} // setNamezh()

	/**
	 * Set the value of [nameen] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setNameen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nameen !== $v) {
			$this->nameen = $v;
			$this->modifiedColumns[] = Routes2011Peer::NAMEEN;
		}

		return $this;
	} // setNameen()

	/**
	 * Set the value of [pathattributeid] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setPathattributeid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pathattributeid !== $v) {
			$this->pathattributeid = $v;
			$this->modifiedColumns[] = Routes2011Peer::PATHATTRIBUTEID;
		}

		return $this;
	} // setPathattributeid()

	/**
	 * Set the value of [pathattributename] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setPathattributename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pathattributename !== $v) {
			$this->pathattributename = $v;
			$this->modifiedColumns[] = Routes2011Peer::PATHATTRIBUTENAME;
		}

		return $this;
	} // setPathattributename()

	/**
	 * Set the value of [pathattributeename] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setPathattributeename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pathattributeename !== $v) {
			$this->pathattributeename = $v;
			$this->modifiedColumns[] = Routes2011Peer::PATHATTRIBUTEENAME;
		}

		return $this;
	} // setPathattributeename()

	/**
	 * Set the value of [buildperiod] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setBuildperiod($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->buildperiod !== $v) {
			$this->buildperiod = $v;
			$this->modifiedColumns[] = Routes2011Peer::BUILDPERIOD;
		}

		return $this;
	} // setBuildperiod()

	/**
	 * Set the value of [departurezh] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setDeparturezh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->departurezh !== $v) {
			$this->departurezh = $v;
			$this->modifiedColumns[] = Routes2011Peer::DEPARTUREZH;
		}

		return $this;
	} // setDeparturezh()

	/**
	 * Set the value of [departureen] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setDepartureen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->departureen !== $v) {
			$this->departureen = $v;
			$this->modifiedColumns[] = Routes2011Peer::DEPARTUREEN;
		}

		return $this;
	} // setDepartureen()

	/**
	 * Set the value of [destinationzh] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setDestinationzh($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->destinationzh !== $v) {
			$this->destinationzh = $v;
			$this->modifiedColumns[] = Routes2011Peer::DESTINATIONZH;
		}

		return $this;
	} // setDestinationzh()

	/**
	 * Set the value of [destinationen] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setDestinationen($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->destinationen !== $v) {
			$this->destinationen = $v;
			$this->modifiedColumns[] = Routes2011Peer::DESTINATIONEN;
		}

		return $this;
	} // setDestinationen()

	/**
	 * Set the value of [realsequence] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setRealsequence($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->realsequence !== $v) {
			$this->realsequence = $v;
			$this->modifiedColumns[] = Routes2011Peer::REALSEQUENCE;
		}

		return $this;
	} // setRealsequence()

	/**
	 * Set the value of [distance] column.
	 * 
	 * @param      int $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setDistance($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->distance !== $v) {
			$this->distance = $v;
			$this->modifiedColumns[] = Routes2011Peer::DISTANCE;
		}

		return $this;
	} // setDistance()

	/**
	 * Set the value of [gofirstbustime] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setGofirstbustime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->gofirstbustime !== $v) {
			$this->gofirstbustime = $v;
			$this->modifiedColumns[] = Routes2011Peer::GOFIRSTBUSTIME;
		}

		return $this;
	} // setGofirstbustime()

	/**
	 * Set the value of [backfirstbustime] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setBackfirstbustime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->backfirstbustime !== $v) {
			$this->backfirstbustime = $v;
			$this->modifiedColumns[] = Routes2011Peer::BACKFIRSTBUSTIME;
		}

		return $this;
	} // setBackfirstbustime()

	/**
	 * Set the value of [golastbustime] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setGolastbustime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->golastbustime !== $v) {
			$this->golastbustime = $v;
			$this->modifiedColumns[] = Routes2011Peer::GOLASTBUSTIME;
		}

		return $this;
	} // setGolastbustime()

	/**
	 * Set the value of [backlastbustime] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setBacklastbustime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->backlastbustime !== $v) {
			$this->backlastbustime = $v;
			$this->modifiedColumns[] = Routes2011Peer::BACKLASTBUSTIME;
		}

		return $this;
	} // setBacklastbustime()

	/**
	 * Set the value of [offpeakheadway] column.
	 * 
	 * @param      string $v new value
	 * @return     Routes2011 The current object (for fluent API support)
	 */
	public function setOffpeakheadway($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->offpeakheadway !== $v) {
			$this->offpeakheadway = $v;
			$this->modifiedColumns[] = Routes2011Peer::OFFPEAKHEADWAY;
		}

		return $this;
	} // setOffpeakheadway()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->routeid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->providerid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->providername = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->namezh = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->nameen = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pathattributeid = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->pathattributename = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->pathattributeename = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->buildperiod = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->departurezh = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->departureen = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->destinationzh = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->destinationen = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->realsequence = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->distance = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->gofirstbustime = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->backfirstbustime = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->golastbustime = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->backlastbustime = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->offpeakheadway = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 21; // 21 = Routes2011Peer::NUM_HYDRATE_COLUMNS.

		} catch (Exception $e) {
			throw new PropelException("Error populating Routes2011 object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Routes2011Peer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = Routes2011Peer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Routes2011Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$deleteQuery = Routes2011Query::create()
				->filterByPrimaryKey($this->getPrimaryKey());
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRoutes2011:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}

			if ($ret) {
				$deleteQuery->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRoutes2011:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(Routes2011Peer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRoutes2011:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRoutes2011:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				Routes2011Peer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (Exception $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() || $this->isModified()) {
				// persist changes
				if ($this->isNew()) {
					$this->doInsert($con);
				} else {
					$this->doUpdate($con);
				}
				$affectedRows += 1;
				$this->resetModified();
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Insert the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @throws     PropelException
	 * @see        doSave()
	 */
	protected function doInsert(PropelPDO $con)
	{
		$modifiedColumns = array();
		$index = 0;

		$this->modifiedColumns[] = Routes2011Peer::ID;
		if (null !== $this->id) {
			throw new PropelException('Cannot insert a value for auto-increment primary key (' . Routes2011Peer::ID . ')');
		}
		if (null === $this->id) {
			try {				
				$stmt = $con->query("SELECT nextval('routes_2011_id_seq')");
				$row = $stmt->fetch(PDO::FETCH_NUM);
				$this->id = $row[0];
			} catch (Exception $e) {
				throw new PropelException('Unable to get sequence id.', $e);
			}
		}


		 // check the columns in natural order for more readable SQL queries
		if ($this->isColumnModified(Routes2011Peer::ID)) {
			$modifiedColumns[':p' . $index++]  = 'ID';
		}
		if ($this->isColumnModified(Routes2011Peer::ROUTEID)) {
			$modifiedColumns[':p' . $index++]  = 'ROUTEID';
		}
		if ($this->isColumnModified(Routes2011Peer::PROVIDERID)) {
			$modifiedColumns[':p' . $index++]  = 'PROVIDERID';
		}
		if ($this->isColumnModified(Routes2011Peer::PROVIDERNAME)) {
			$modifiedColumns[':p' . $index++]  = 'PROVIDERNAME';
		}
		if ($this->isColumnModified(Routes2011Peer::NAMEZH)) {
			$modifiedColumns[':p' . $index++]  = 'NAMEZH';
		}
		if ($this->isColumnModified(Routes2011Peer::NAMEEN)) {
			$modifiedColumns[':p' . $index++]  = 'NAMEEN';
		}
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTEID)) {
			$modifiedColumns[':p' . $index++]  = 'PATHATTRIBUTEID';
		}
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTENAME)) {
			$modifiedColumns[':p' . $index++]  = 'PATHATTRIBUTENAME';
		}
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTEENAME)) {
			$modifiedColumns[':p' . $index++]  = 'PATHATTRIBUTEENAME';
		}
		if ($this->isColumnModified(Routes2011Peer::BUILDPERIOD)) {
			$modifiedColumns[':p' . $index++]  = 'BUILDPERIOD';
		}
		if ($this->isColumnModified(Routes2011Peer::DEPARTUREZH)) {
			$modifiedColumns[':p' . $index++]  = 'DEPARTUREZH';
		}
		if ($this->isColumnModified(Routes2011Peer::DEPARTUREEN)) {
			$modifiedColumns[':p' . $index++]  = 'DEPARTUREEN';
		}
		if ($this->isColumnModified(Routes2011Peer::DESTINATIONZH)) {
			$modifiedColumns[':p' . $index++]  = 'DESTINATIONZH';
		}
		if ($this->isColumnModified(Routes2011Peer::DESTINATIONEN)) {
			$modifiedColumns[':p' . $index++]  = 'DESTINATIONEN';
		}
		if ($this->isColumnModified(Routes2011Peer::REALSEQUENCE)) {
			$modifiedColumns[':p' . $index++]  = 'REALSEQUENCE';
		}
		if ($this->isColumnModified(Routes2011Peer::DISTANCE)) {
			$modifiedColumns[':p' . $index++]  = 'DISTANCE';
		}
		if ($this->isColumnModified(Routes2011Peer::GOFIRSTBUSTIME)) {
			$modifiedColumns[':p' . $index++]  = 'GOFIRSTBUSTIME';
		}
		if ($this->isColumnModified(Routes2011Peer::BACKFIRSTBUSTIME)) {
			$modifiedColumns[':p' . $index++]  = 'BACKFIRSTBUSTIME';
		}
		if ($this->isColumnModified(Routes2011Peer::GOLASTBUSTIME)) {
			$modifiedColumns[':p' . $index++]  = 'GOLASTBUSTIME';
		}
		if ($this->isColumnModified(Routes2011Peer::BACKLASTBUSTIME)) {
			$modifiedColumns[':p' . $index++]  = 'BACKLASTBUSTIME';
		}
		if ($this->isColumnModified(Routes2011Peer::OFFPEAKHEADWAY)) {
			$modifiedColumns[':p' . $index++]  = 'OFFPEAKHEADWAY';
		}

		$sql = sprintf(
			'INSERT INTO routes_2011 (%s) VALUES (%s)',
			implode(', ', $modifiedColumns),
			implode(', ', array_keys($modifiedColumns))
		);

		try {
			$stmt = $con->prepare($sql);
			foreach ($modifiedColumns as $identifier => $columnName) {
				switch ($columnName) {
					case 'ID':
						$stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
						break;
					case 'ROUTEID':
						$stmt->bindValue($identifier, $this->routeid, PDO::PARAM_INT);
						break;
					case 'PROVIDERID':
						$stmt->bindValue($identifier, $this->providerid, PDO::PARAM_INT);
						break;
					case 'PROVIDERNAME':
						$stmt->bindValue($identifier, $this->providername, PDO::PARAM_STR);
						break;
					case 'NAMEZH':
						$stmt->bindValue($identifier, $this->namezh, PDO::PARAM_STR);
						break;
					case 'NAMEEN':
						$stmt->bindValue($identifier, $this->nameen, PDO::PARAM_STR);
						break;
					case 'PATHATTRIBUTEID':
						$stmt->bindValue($identifier, $this->pathattributeid, PDO::PARAM_INT);
						break;
					case 'PATHATTRIBUTENAME':
						$stmt->bindValue($identifier, $this->pathattributename, PDO::PARAM_STR);
						break;
					case 'PATHATTRIBUTEENAME':
						$stmt->bindValue($identifier, $this->pathattributeename, PDO::PARAM_STR);
						break;
					case 'BUILDPERIOD':
						$stmt->bindValue($identifier, $this->buildperiod, PDO::PARAM_INT);
						break;
					case 'DEPARTUREZH':
						$stmt->bindValue($identifier, $this->departurezh, PDO::PARAM_STR);
						break;
					case 'DEPARTUREEN':
						$stmt->bindValue($identifier, $this->departureen, PDO::PARAM_STR);
						break;
					case 'DESTINATIONZH':
						$stmt->bindValue($identifier, $this->destinationzh, PDO::PARAM_STR);
						break;
					case 'DESTINATIONEN':
						$stmt->bindValue($identifier, $this->destinationen, PDO::PARAM_STR);
						break;
					case 'REALSEQUENCE':
						$stmt->bindValue($identifier, $this->realsequence, PDO::PARAM_INT);
						break;
					case 'DISTANCE':
						$stmt->bindValue($identifier, $this->distance, PDO::PARAM_INT);
						break;
					case 'GOFIRSTBUSTIME':
						$stmt->bindValue($identifier, $this->gofirstbustime, PDO::PARAM_STR);
						break;
					case 'BACKFIRSTBUSTIME':
						$stmt->bindValue($identifier, $this->backfirstbustime, PDO::PARAM_STR);
						break;
					case 'GOLASTBUSTIME':
						$stmt->bindValue($identifier, $this->golastbustime, PDO::PARAM_STR);
						break;
					case 'BACKLASTBUSTIME':
						$stmt->bindValue($identifier, $this->backlastbustime, PDO::PARAM_STR);
						break;
					case 'OFFPEAKHEADWAY':
						$stmt->bindValue($identifier, $this->offpeakheadway, PDO::PARAM_STR);
						break;
				}
			}
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
		}

		$this->setNew(false);
	}

	/**
	 * Update the row in the database.
	 *
	 * @param      PropelPDO $con
	 *
	 * @see        doSave()
	 */
	protected function doUpdate(PropelPDO $con)
	{
		$selectCriteria = $this->buildPkeyCriteria();
		$valuesCriteria = $this->buildCriteria();
		BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
	}

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = Routes2011Peer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Routes2011Peer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getRouteid();
				break;
			case 2:
				return $this->getProviderid();
				break;
			case 3:
				return $this->getProvidername();
				break;
			case 4:
				return $this->getNamezh();
				break;
			case 5:
				return $this->getNameen();
				break;
			case 6:
				return $this->getPathattributeid();
				break;
			case 7:
				return $this->getPathattributename();
				break;
			case 8:
				return $this->getPathattributeename();
				break;
			case 9:
				return $this->getBuildperiod();
				break;
			case 10:
				return $this->getDeparturezh();
				break;
			case 11:
				return $this->getDepartureen();
				break;
			case 12:
				return $this->getDestinationzh();
				break;
			case 13:
				return $this->getDestinationen();
				break;
			case 14:
				return $this->getRealsequence();
				break;
			case 15:
				return $this->getDistance();
				break;
			case 16:
				return $this->getGofirstbustime();
				break;
			case 17:
				return $this->getBackfirstbustime();
				break;
			case 18:
				return $this->getGolastbustime();
				break;
			case 19:
				return $this->getBacklastbustime();
				break;
			case 20:
				return $this->getOffpeakheadway();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
	{
		if (isset($alreadyDumpedObjects['Routes2011'][$this->getPrimaryKey()])) {
			return '*RECURSION*';
		}
		$alreadyDumpedObjects['Routes2011'][$this->getPrimaryKey()] = true;
		$keys = Routes2011Peer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getRouteid(),
			$keys[2] => $this->getProviderid(),
			$keys[3] => $this->getProvidername(),
			$keys[4] => $this->getNamezh(),
			$keys[5] => $this->getNameen(),
			$keys[6] => $this->getPathattributeid(),
			$keys[7] => $this->getPathattributename(),
			$keys[8] => $this->getPathattributeename(),
			$keys[9] => $this->getBuildperiod(),
			$keys[10] => $this->getDeparturezh(),
			$keys[11] => $this->getDepartureen(),
			$keys[12] => $this->getDestinationzh(),
			$keys[13] => $this->getDestinationen(),
			$keys[14] => $this->getRealsequence(),
			$keys[15] => $this->getDistance(),
			$keys[16] => $this->getGofirstbustime(),
			$keys[17] => $this->getBackfirstbustime(),
			$keys[18] => $this->getGolastbustime(),
			$keys[19] => $this->getBacklastbustime(),
			$keys[20] => $this->getOffpeakheadway(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = Routes2011Peer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setRouteid($value);
				break;
			case 2:
				$this->setProviderid($value);
				break;
			case 3:
				$this->setProvidername($value);
				break;
			case 4:
				$this->setNamezh($value);
				break;
			case 5:
				$this->setNameen($value);
				break;
			case 6:
				$this->setPathattributeid($value);
				break;
			case 7:
				$this->setPathattributename($value);
				break;
			case 8:
				$this->setPathattributeename($value);
				break;
			case 9:
				$this->setBuildperiod($value);
				break;
			case 10:
				$this->setDeparturezh($value);
				break;
			case 11:
				$this->setDepartureen($value);
				break;
			case 12:
				$this->setDestinationzh($value);
				break;
			case 13:
				$this->setDestinationen($value);
				break;
			case 14:
				$this->setRealsequence($value);
				break;
			case 15:
				$this->setDistance($value);
				break;
			case 16:
				$this->setGofirstbustime($value);
				break;
			case 17:
				$this->setBackfirstbustime($value);
				break;
			case 18:
				$this->setGolastbustime($value);
				break;
			case 19:
				$this->setBacklastbustime($value);
				break;
			case 20:
				$this->setOffpeakheadway($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = Routes2011Peer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRouteid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProviderid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setProvidername($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNamezh($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setNameen($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPathattributeid($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPathattributename($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPathattributeename($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setBuildperiod($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDeparturezh($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDepartureen($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDestinationzh($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setDestinationen($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setRealsequence($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDistance($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setGofirstbustime($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setBackfirstbustime($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setGolastbustime($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setBacklastbustime($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setOffpeakheadway($arr[$keys[20]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(Routes2011Peer::DATABASE_NAME);

		if ($this->isColumnModified(Routes2011Peer::ID)) $criteria->add(Routes2011Peer::ID, $this->id);
		if ($this->isColumnModified(Routes2011Peer::ROUTEID)) $criteria->add(Routes2011Peer::ROUTEID, $this->routeid);
		if ($this->isColumnModified(Routes2011Peer::PROVIDERID)) $criteria->add(Routes2011Peer::PROVIDERID, $this->providerid);
		if ($this->isColumnModified(Routes2011Peer::PROVIDERNAME)) $criteria->add(Routes2011Peer::PROVIDERNAME, $this->providername);
		if ($this->isColumnModified(Routes2011Peer::NAMEZH)) $criteria->add(Routes2011Peer::NAMEZH, $this->namezh);
		if ($this->isColumnModified(Routes2011Peer::NAMEEN)) $criteria->add(Routes2011Peer::NAMEEN, $this->nameen);
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTEID)) $criteria->add(Routes2011Peer::PATHATTRIBUTEID, $this->pathattributeid);
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTENAME)) $criteria->add(Routes2011Peer::PATHATTRIBUTENAME, $this->pathattributename);
		if ($this->isColumnModified(Routes2011Peer::PATHATTRIBUTEENAME)) $criteria->add(Routes2011Peer::PATHATTRIBUTEENAME, $this->pathattributeename);
		if ($this->isColumnModified(Routes2011Peer::BUILDPERIOD)) $criteria->add(Routes2011Peer::BUILDPERIOD, $this->buildperiod);
		if ($this->isColumnModified(Routes2011Peer::DEPARTUREZH)) $criteria->add(Routes2011Peer::DEPARTUREZH, $this->departurezh);
		if ($this->isColumnModified(Routes2011Peer::DEPARTUREEN)) $criteria->add(Routes2011Peer::DEPARTUREEN, $this->departureen);
		if ($this->isColumnModified(Routes2011Peer::DESTINATIONZH)) $criteria->add(Routes2011Peer::DESTINATIONZH, $this->destinationzh);
		if ($this->isColumnModified(Routes2011Peer::DESTINATIONEN)) $criteria->add(Routes2011Peer::DESTINATIONEN, $this->destinationen);
		if ($this->isColumnModified(Routes2011Peer::REALSEQUENCE)) $criteria->add(Routes2011Peer::REALSEQUENCE, $this->realsequence);
		if ($this->isColumnModified(Routes2011Peer::DISTANCE)) $criteria->add(Routes2011Peer::DISTANCE, $this->distance);
		if ($this->isColumnModified(Routes2011Peer::GOFIRSTBUSTIME)) $criteria->add(Routes2011Peer::GOFIRSTBUSTIME, $this->gofirstbustime);
		if ($this->isColumnModified(Routes2011Peer::BACKFIRSTBUSTIME)) $criteria->add(Routes2011Peer::BACKFIRSTBUSTIME, $this->backfirstbustime);
		if ($this->isColumnModified(Routes2011Peer::GOLASTBUSTIME)) $criteria->add(Routes2011Peer::GOLASTBUSTIME, $this->golastbustime);
		if ($this->isColumnModified(Routes2011Peer::BACKLASTBUSTIME)) $criteria->add(Routes2011Peer::BACKLASTBUSTIME, $this->backlastbustime);
		if ($this->isColumnModified(Routes2011Peer::OFFPEAKHEADWAY)) $criteria->add(Routes2011Peer::OFFPEAKHEADWAY, $this->offpeakheadway);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(Routes2011Peer::DATABASE_NAME);
		$criteria->add(Routes2011Peer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Routes2011 (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @param      boolean $makeNew Whether to reset autoincrement PKs and make the object new.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
	{
		$copyObj->setRouteid($this->getRouteid());
		$copyObj->setProviderid($this->getProviderid());
		$copyObj->setProvidername($this->getProvidername());
		$copyObj->setNamezh($this->getNamezh());
		$copyObj->setNameen($this->getNameen());
		$copyObj->setPathattributeid($this->getPathattributeid());
		$copyObj->setPathattributename($this->getPathattributename());
		$copyObj->setPathattributeename($this->getPathattributeename());
		$copyObj->setBuildperiod($this->getBuildperiod());
		$copyObj->setDeparturezh($this->getDeparturezh());
		$copyObj->setDepartureen($this->getDepartureen());
		$copyObj->setDestinationzh($this->getDestinationzh());
		$copyObj->setDestinationen($this->getDestinationen());
		$copyObj->setRealsequence($this->getRealsequence());
		$copyObj->setDistance($this->getDistance());
		$copyObj->setGofirstbustime($this->getGofirstbustime());
		$copyObj->setBackfirstbustime($this->getBackfirstbustime());
		$copyObj->setGolastbustime($this->getGolastbustime());
		$copyObj->setBacklastbustime($this->getBacklastbustime());
		$copyObj->setOffpeakheadway($this->getOffpeakheadway());
		if ($makeNew) {
			$copyObj->setNew(true);
			$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
		}
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Routes2011 Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     Routes2011Peer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new Routes2011Peer();
		}
		return self::$peer;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->routeid = null;
		$this->providerid = null;
		$this->providername = null;
		$this->namezh = null;
		$this->nameen = null;
		$this->pathattributeid = null;
		$this->pathattributename = null;
		$this->pathattributeename = null;
		$this->buildperiod = null;
		$this->departurezh = null;
		$this->departureen = null;
		$this->destinationzh = null;
		$this->destinationen = null;
		$this->realsequence = null;
		$this->distance = null;
		$this->gofirstbustime = null;
		$this->backfirstbustime = null;
		$this->golastbustime = null;
		$this->backlastbustime = null;
		$this->offpeakheadway = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all references to other model objects or collections of model objects.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect
	 * objects with circular references (even in PHP 5.3). This is currently necessary
	 * when using Propel in certain daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all referrer objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	/**
	 * Return the string representation of this object
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->exportTo(Routes2011Peer::DEFAULT_STRING_FORMAT);
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseRoutes2011:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}

		return parent::__call($name, $params);
	}

} // BaseRoutes2011
